export const SITEMAP_CORE_PATHS = [
  "",
  "/phones",
  "/accessories",
  "/accessories/airpods-price-in-pakistan",
  "/accessories/earbuds-price-in-pakistan",
  "/accessories/headphones-price-in-pakistan",
  "/mobile-prices-in-pakistan",
  "/used-mobile-phones",
  "/used-mobile-phones/under-20000",
  "/used-mobile-phones/under-30000",
  "/used-mobile-phones/under-50000",
  "/used-mobile-phones/under-100000",
  "/iphone-18-price-in-pakistan",
  "/iphone-18-pro-price-in-pakistan",
  "/iphone-18-pro-max-price-in-pakistan",
  "/best-mobile-phones/under-30000",
  "/best-mobile-phones/under-50000",
  "/best-mobile-phones/under-100000",
  "/guides",
  "/guides/best-mobile-markets-in-pakistan",
  "/guides/best-mobile-market-in-karachi",
  "/guides/best-mobile-market-in-lahore",
  "/guides/best-mobile-market-in-islamabad",
  "/guides/best-mobile-market-in-rawalpindi",
  "/guides/best-mobile-market-in-multan",
  "/guides/best-mobile-market-in-faisalabad",
  "/guides/best-mobile-market-in-peshawar",
  "/guides/best-mobile-market-in-hyderabad",
  "/guides/best-mobile-market-in-quetta",
  "/guides/best-mobile-market-in-mardan",
  "/guides/best-mobile-market-in-gujranwala",
  "/guides/best-mobile-market-in-swat",
  "/guides/best-mobile-market-in-sukkur",
  "/guides/best-mobile-market-in-sialkot",
  "/guides/best-mobile-market-in-gujrat",
  "/guides/best-mobile-market-in-kasur",
  "/guides/best-mobile-market-in-jhang",
  "/guides/best-mobile-market-in-taxila",
  "/guides/best-mobile-market-in-abbottabad",
  "/guides/best-mobile-market-in-swabi",
  "/guides/best-mobile-market-in-buner",
  "/guides/best-mobile-market-in-kohat",
  "/guides/best-mobile-market-in-karak",
  "/guides/best-mobile-market-in-larkana",
  "/guides/authorized-mobile-dealers-in-pakistan",
  "/guides/inspect-used-phone",
  "/guides/buy-used-phone",
  "/guides/pta-status",
  "/guides/pta-tax",
  "/guides/battery-health",
  "/guides/common-scams",
  "/guides/fake-airpods",
  "/guides/buy-used-airpods",
  "/about",
  "/contact",
  "/buyer-safety",
  "/privacy",
  "/terms",
  "/seller-terms",
  "/rules",
  "/prohibited",
  "/return-policy",
];

/**
 * Last real content change for core pages (yyyy-mm-dd). Only pages whose update date
 * is known are listed; the rest are sent without lastmod rather than a fake date.
 */
export const SITEMAP_CORE_LASTMOD: Record<string, string> = {
  "/guides/pta-status": "2026-10-02",
  "/best-mobile-phones/under-30000": "2026-10-02",
  "/best-mobile-phones/under-50000": "2026-10-02",
  "/best-mobile-phones/under-100000": "2026-10-02",
  "/guides/best-mobile-market-in-multan": "2026-10-04",
  "/guides/best-mobile-market-in-faisalabad": "2026-10-04",
  "/guides/best-mobile-market-in-peshawar": "2026-10-04",
  "/guides/best-mobile-market-in-hyderabad": "2026-10-04",
  "/guides/best-mobile-market-in-quetta": "2026-10-04",
  "/guides/best-mobile-market-in-mardan": "2026-10-04",
  "/guides/best-mobile-market-in-gujranwala": "2026-10-04",
  "/guides/best-mobile-market-in-swat": "2026-10-04",
  "/guides/best-mobile-market-in-sukkur": "2026-10-04",
  "/guides/best-mobile-market-in-sialkot": "2026-10-04",
  "/guides/best-mobile-market-in-gujrat": "2026-10-04",
  "/guides/best-mobile-market-in-kasur": "2026-10-04",
  "/guides/best-mobile-market-in-jhang": "2026-10-04",
  "/guides/best-mobile-market-in-taxila": "2026-10-04",
  "/guides/best-mobile-market-in-abbottabad": "2026-10-04",
  "/guides/best-mobile-market-in-swabi": "2026-10-04",
  "/guides/best-mobile-market-in-buner": "2026-10-04",
  "/guides/best-mobile-market-in-kohat": "2026-10-04",
  "/guides/best-mobile-market-in-karak": "2026-10-04",
  "/guides/best-mobile-market-in-larkana": "2026-10-04",
  "/guides/inspect-used-phone": "2026-10-02",
  "/guides/battery-health": "2026-10-02",
  "/guides/common-scams": "2026-10-02",
  "/guides/buy-used-phone": "2026-10-02",
  "/guides/pta-tax": "2026-10-02",
  "/iphone-18-price-in-pakistan": "2026-10-02",
  "/iphone-18-pro-price-in-pakistan": "2026-10-02",
  "/iphone-18-pro-max-price-in-pakistan": "2026-10-02",
  "/guides/best-mobile-markets-in-pakistan": "2026-10-04",
  "/guides/best-mobile-market-in-karachi": "2026-10-04",
  "/guides/best-mobile-market-in-lahore": "2026-10-04",
  "/guides/best-mobile-market-in-islamabad": "2026-10-04",
  "/guides/best-mobile-market-in-rawalpindi": "2026-10-04",
  "/guides/authorized-mobile-dealers-in-pakistan": "2026-10-01",
  "/accessories/airpods-price-in-pakistan": "2026-10-04",
  "/accessories/earbuds-price-in-pakistan": "2026-10-04",
  "/accessories/headphones-price-in-pakistan": "2026-10-04",
  "/guides/fake-airpods": "2026-10-04",
  "/guides/buy-used-airpods": "2026-10-04",
  "/about": "2026-10-02",
  "/contact": "2026-10-02",
};
